apiVersion: v1
kind: PersistentVolume
metadata:
  name: fsx-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: fsx-sc
  csi:
    driver: fsx.csi.aws.com
    volumeHandle: fs-0b88f4c7b6f8772d7
    volumeAttributes:
      dnsname: fs-0b88f4c7b6f8772d7.fsx.us-west-2.amazonaws.com
